import { Response } from 'express';
import bcrypt from 'bcryptjs';
import { randomBytes } from 'crypto';
import { AppDataSource } from '../config/database';
import { User, UserRole } from '../entities/User';
import { Parent } from '../entities/Parent';
import { Student } from '../entities/Student';
import { AuthRequest } from '../middleware/auth';

const generateTemporaryPassword = () => {
  return `Temp-${randomBytes(4).toString('hex')}-${Date.now().toString().slice(-4)}`;
};

/** Admin: List all parents with stats */
export const listParents = async (req: AuthRequest, res: Response) => {
  try {
    if (!req.user || (req.user.role !== UserRole.ADMIN && req.user.role !== UserRole.SUPERADMIN)) {
      return res.status(403).json({ message: 'Admin access required' });
    }

    if (!AppDataSource.isInitialized) await AppDataSource.initialize();

    const { search } = req.query;
    const parentRepository = AppDataSource.getRepository(Parent);
    const studentRepository = AppDataSource.getRepository(Student);

    let qb = parentRepository
      .createQueryBuilder('parent')
      .leftJoinAndSelect('parent.students', 'students')
      .orderBy('parent.firstName', 'ASC')
      .addOrderBy('parent.lastName', 'ASC');

    if (search && typeof search === 'string' && search.trim()) {
      const term = `%${search.trim()}%`;
      qb = qb.andWhere(
        '(parent.firstName ILIKE :term OR parent.lastName ILIKE :term OR parent.email ILIKE :term OR parent.phoneNumber ILIKE :term)',
        { term }
      );
    }

    const parents = await qb.getMany();

    // Stats
    const notLinked = parents.filter((p) => !p.students || p.students.length === 0).length;
    const linkedStudentsCount = parents.reduce((sum, p) => sum + (p.students?.length || 0), 0);
    const studentsWithAccounts = await studentRepository
      .createQueryBuilder('s')
      .where('s.userId IS NOT NULL')
      .getCount();

    const items = parents.map((p) => ({
      id: p.id,
      firstName: p.firstName,
      lastName: p.lastName,
      email: p.email,
      phoneNumber: p.phoneNumber,
      address: p.address,
      gender: p.gender,
      userId: p.userId,
      studentsCount: p.students?.length || 0,
      students: (p.students || []).map((s) => ({
        id: s.id,
        firstName: s.firstName,
        lastName: s.lastName,
        studentNumber: s.studentNumber,
        hasLoginAccount: !!s.userId,
      })),
    }));

    res.json({
      parents: items,
      stats: {
        total: items.length,
        notLinked,
        linkedStudents: linkedStudentsCount,
        studentAccounts: studentsWithAccounts,
      },
    });
  } catch (error: any) {
    console.error('listParents error:', error);
    res.status(500).json({ message: 'Server error', error: error.message });
  }
};

/** Admin: Create parent account (User + Parent entity) */
export const createParentAccount = async (req: AuthRequest, res: Response) => {
  try {
    if (!req.user || (req.user.role !== UserRole.ADMIN && req.user.role !== UserRole.SUPERADMIN)) {
      return res.status(403).json({ message: 'Admin access required' });
    }

    if (!AppDataSource.isInitialized) await AppDataSource.initialize();

    const {
      firstName,
      lastName,
      email,
      phoneNumber,
      address,
      gender,
      password,
      generatePassword = true,
    } = req.body || {};

    if (!firstName || !lastName || !email) {
      return res.status(400).json({ message: 'First name, last name, and email are required' });
    }

    const emailStr = String(email).trim();
    const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailPattern.test(emailStr)) {
      return res.status(400).json({ message: 'Please enter a valid email address' });
    }

    const userRepository = AppDataSource.getRepository(User);
    const parentRepository = AppDataSource.getRepository(Parent);

    const trimmedEmail = emailStr.toLowerCase();
    const existingUser = await userRepository.findOne({ where: { email: trimmedEmail } });
    if (existingUser) {
      return res.status(400).json({ message: 'Email already exists' });
    }

    const baseUsername = trimmedEmail.split('@')[0].replace(/\s+/g, '');
    let finalUsername = baseUsername;
    let suffix = 1;
    while (await userRepository.findOne({ where: { username: finalUsername } })) {
      finalUsername = `${baseUsername}${suffix++}`;
    }

    let plainPassword = password ? String(password).trim() : '';
    const autoGenerated = !plainPassword;
    if (!plainPassword) plainPassword = generateTemporaryPassword();
    if (plainPassword.length < 8) {
      return res.status(400).json({ message: 'Password must be at least 8 characters' });
    }

    const hashedPassword = await bcrypt.hash(plainPassword, 10);
    const user = userRepository.create({
      email: trimmedEmail,
      username: finalUsername,
      password: hashedPassword,
      role: UserRole.PARENT,
      mustChangePassword: autoGenerated,
      isTemporaryAccount: autoGenerated,
      isActive: true,
    });
    await userRepository.save(user);

    const parent = parentRepository.create({
      firstName: String(firstName).trim(),
      lastName: String(lastName).trim(),
      email: trimmedEmail,
      phoneNumber: phoneNumber ? String(phoneNumber).trim() : null,
      address: address ? String(address).trim() : null,
      gender: gender ? String(gender).trim() : null,
      userId: user.id,
    });
    await parentRepository.save(parent);

    res.status(201).json({
      message: 'Parent account created successfully',
      parent: {
        id: parent.id,
        firstName: parent.firstName,
        lastName: parent.lastName,
        email: parent.email,
      },
      user: { id: user.id, username: user.username },
      temporaryCredentials: autoGenerated ? { password: plainPassword } : undefined,
    });
  } catch (error: any) {
    console.error('createParentAccount error:', error);
    res.status(500).json({ message: 'Server error', error: error.message });
  }
};

/** Admin: Reset parent password */
export const resetParentPassword = async (req: AuthRequest, res: Response) => {
  try {
    if (!req.user || (req.user.role !== UserRole.ADMIN && req.user.role !== UserRole.SUPERADMIN)) {
      return res.status(403).json({ message: 'Admin access required' });
    }

    if (!AppDataSource.isInitialized) await AppDataSource.initialize();

    const { id } = req.params;
    const { newPassword, generatePassword = false } = req.body;

    if (!id) return res.status(400).json({ message: 'Parent ID is required' });

    let plainPassword: string;
    if (generatePassword) {
      plainPassword = generateTemporaryPassword();
    } else {
      if (!newPassword || newPassword.length < 8) {
        return res.status(400).json({ message: 'New password (min 8 chars) is required when not generating' });
      }
      plainPassword = String(newPassword);
    }

    const parentRepository = AppDataSource.getRepository(Parent);
    const userRepository = AppDataSource.getRepository(User);

    const parent = await parentRepository.findOne({ where: { id } });
    if (!parent) return res.status(404).json({ message: 'Parent not found' });
    if (!parent.userId) return res.status(400).json({ message: 'Parent has no login account' });

    const user = await userRepository.findOne({ where: { id: parent.userId } });
    if (!user) return res.status(404).json({ message: 'User not found' });

    user.password = await bcrypt.hash(plainPassword, 10);
    user.mustChangePassword = generatePassword;
    user.isTemporaryAccount = generatePassword;
    await userRepository.save(user);

    res.json({
      message: 'Parent password reset successfully',
      ...(generatePassword && { temporaryPassword: plainPassword }),
    });
  } catch (error: any) {
    console.error('resetParentPassword error:', error);
    res.status(500).json({ message: 'Server error', error: error.message });
  }
};

/** Admin: Get parent by ID with details */
export const getParentById = async (req: AuthRequest, res: Response) => {
  try {
    if (!req.user || (req.user.role !== UserRole.ADMIN && req.user.role !== UserRole.SUPERADMIN)) {
      return res.status(403).json({ message: 'Admin access required' });
    }

    const { id } = req.params;
    const parentRepository = AppDataSource.getRepository(Parent);

    const parent = await parentRepository.findOne({
      where: { id },
      relations: ['students', 'students.classEntity'],
    });
    if (!parent) return res.status(404).json({ message: 'Parent not found' });

    res.json({
      id: parent.id,
      firstName: parent.firstName,
      lastName: parent.lastName,
      email: parent.email,
      phoneNumber: parent.phoneNumber,
      address: parent.address,
      gender: parent.gender,
      userId: parent.userId,
      students: (parent.students || []).map((s) => ({
        id: s.id,
        firstName: s.firstName,
        lastName: s.lastName,
        studentNumber: s.studentNumber,
        classEntity: s.classEntity,
        hasLoginAccount: !!s.userId,
      })),
    });
  } catch (error: any) {
    console.error('getParentById error:', error);
    res.status(500).json({ message: 'Server error', error: error.message });
  }
};

const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

/** Admin: Update parent */
export const updateParent = async (req: AuthRequest, res: Response) => {
  try {
    if (!req.user || (req.user.role !== UserRole.ADMIN && req.user.role !== UserRole.SUPERADMIN)) {
      return res.status(403).json({ message: 'Admin access required' });
    }

    const { id } = req.params;
    const { firstName, lastName, email, phoneNumber, address, gender } = req.body || {};

    const parentRepository = AppDataSource.getRepository(Parent);
    const userRepository = AppDataSource.getRepository(User);

    const parent = await parentRepository.findOne({ where: { id } });
    if (!parent) return res.status(404).json({ message: 'Parent not found' });

    if (firstName !== undefined) parent.firstName = String(firstName).trim();
    if (lastName !== undefined) parent.lastName = String(lastName).trim();

    if (email !== undefined) {
      const emailVal = email ? String(email).trim() : '';
      if (emailVal) {
        if (!EMAIL_PATTERN.test(emailVal)) {
          return res.status(400).json({ message: 'Please enter a valid email address' });
        }
        const trimmedEmail = emailVal.toLowerCase();
        const existingUser = await userRepository.findOne({ where: { email: trimmedEmail } });
        if (existingUser && existingUser.id !== parent.userId) {
          return res.status(400).json({ message: 'Email is already in use by another account' });
        }
        parent.email = trimmedEmail;
      } else {
        parent.email = null;
      }
    }
    if (phoneNumber !== undefined) parent.phoneNumber = phoneNumber ? String(phoneNumber).trim() : null;
    if (address !== undefined) parent.address = address ? String(address).trim() : null;
    if (gender !== undefined) parent.gender = gender ? String(gender).trim() : null;

    await parentRepository.save(parent);

    if (parent.userId && (email !== undefined || parent.email)) {
      const user = await userRepository.findOne({ where: { id: parent.userId } });
      if (user && email !== undefined) {
        user.email = parent.email;
        await userRepository.save(user);
      }
    }

    res.json({ message: 'Parent updated successfully', parent });
  } catch (error: any) {
    console.error('updateParent error:', error);
    res.status(500).json({ message: 'Server error', error: error.message });
  }
};

/** Admin: Delete parent (unlinks students, removes parent and user) */
export const deleteParent = async (req: AuthRequest, res: Response) => {
  try {
    if (!req.user || (req.user.role !== UserRole.ADMIN && req.user.role !== UserRole.SUPERADMIN)) {
      return res.status(403).json({ message: 'Admin access required' });
    }

    const { id } = req.params;
    const parentRepository = AppDataSource.getRepository(Parent);
    const studentRepository = AppDataSource.getRepository(Student);
    const userRepository = AppDataSource.getRepository(User);

    const parent = await parentRepository.findOne({ where: { id } });
    if (!parent) return res.status(404).json({ message: 'Parent not found' });

    // Unlink all students
    await studentRepository.update({ parentId: id }, { parentId: null });

    const userId = parent.userId;

    // Delete parent
    await parentRepository.remove(parent);

    // Delete associated user if exists
    if (userId) {
      await userRepository.delete(userId);
    }

    res.json({ message: 'Parent account deleted successfully' });
  } catch (error: any) {
    console.error('deleteParent error:', error);
    res.status(500).json({ message: 'Server error', error: error.message });
  }
};

/** Admin: Link student to parent */
export const adminLinkStudent = async (req: AuthRequest, res: Response) => {
  try {
    if (!req.user || (req.user.role !== UserRole.ADMIN && req.user.role !== UserRole.SUPERADMIN)) {
      return res.status(403).json({ message: 'Admin access required' });
    }

    const { id } = req.params;
    const { studentId } = req.body;

    if (!studentId) return res.status(400).json({ message: 'studentId is required' });

    const parentRepository = AppDataSource.getRepository(Parent);
    const studentRepository = AppDataSource.getRepository(Student);

    const parent = await parentRepository.findOne({ where: { id } });
    if (!parent) return res.status(404).json({ message: 'Parent not found' });

    const student = await studentRepository.findOne({
      where: { id: studentId },
      relations: ['classEntity'],
    });
    if (!student) return res.status(404).json({ message: 'Student not found' });

    if (student.parentId === parent.id) {
      return res.status(400).json({ message: 'Student is already linked to this parent' });
    }

    student.parentId = parent.id;
    await studentRepository.save(student);

    res.json({
      message: 'Student linked successfully',
      student: {
        id: student.id,
        firstName: student.firstName,
        lastName: student.lastName,
        studentNumber: student.studentNumber,
        classEntity: student.classEntity,
      },
    });
  } catch (error: any) {
    console.error('adminLinkStudent error:', error);
    res.status(500).json({ message: 'Server error', error: error.message });
  }
};

/** Admin: Bulk link students to parent */
export const adminBulkLinkStudents = async (req: AuthRequest, res: Response) => {
  try {
    if (!req.user || (req.user.role !== UserRole.ADMIN && req.user.role !== UserRole.SUPERADMIN)) {
      return res.status(403).json({ message: 'Admin access required' });
    }

    const { id } = req.params;
    const { studentIds } = req.body;

    if (!Array.isArray(studentIds) || studentIds.length === 0) {
      return res.status(400).json({ message: 'studentIds array with at least one ID is required' });
    }

    const parentRepository = AppDataSource.getRepository(Parent);
    const studentRepository = AppDataSource.getRepository(Student);

    const parent = await parentRepository.findOne({ where: { id } });
    if (!parent) return res.status(404).json({ message: 'Parent not found' });

    const linked: any[] = [];
    const skipped: { id: string; reason: string }[] = [];

    for (const studentId of studentIds) {
      if (!studentId || typeof studentId !== 'string') continue;
      const student = await studentRepository.findOne({
        where: { id: studentId },
        relations: ['classEntity'],
      });
      if (!student) {
        skipped.push({ id: studentId, reason: 'Student not found' });
        continue;
      }
      if (student.parentId === parent.id) {
        skipped.push({ id: studentId, reason: 'Already linked' });
        continue;
      }
      if (student.parentId && student.parentId !== parent.id) {
        skipped.push({ id: studentId, reason: 'Linked to another parent' });
        continue;
      }
      student.parentId = parent.id;
      await studentRepository.save(student);
      linked.push({
        id: student.id,
        firstName: student.firstName,
        lastName: student.lastName,
        studentNumber: student.studentNumber,
        classEntity: student.classEntity,
      });
    }

    res.json({
      message: linked.length > 0 ? `${linked.length} student(s) linked successfully` : 'No students linked',
      linked,
      skipped: skipped.length > 0 ? skipped : undefined,
    });
  } catch (error: any) {
    console.error('adminBulkLinkStudents error:', error);
    res.status(500).json({ message: 'Server error', error: error.message });
  }
};

/** Admin: Unlink student from parent */
export const adminUnlinkStudent = async (req: AuthRequest, res: Response) => {
  try {
    if (!req.user || (req.user.role !== UserRole.ADMIN && req.user.role !== UserRole.SUPERADMIN)) {
      return res.status(403).json({ message: 'Admin access required' });
    }

    const { id, studentId } = req.params;

    const parentRepository = AppDataSource.getRepository(Parent);
    const studentRepository = AppDataSource.getRepository(Student);

    const parent = await parentRepository.findOne({ where: { id } });
    if (!parent) return res.status(404).json({ message: 'Parent not found' });

    const student = await studentRepository.findOne({ where: { id: studentId } });
    if (!student) return res.status(404).json({ message: 'Student not found' });

    if (student.parentId !== parent.id) {
      return res.status(400).json({ message: 'Student is not linked to this parent' });
    }

    student.parentId = null;
    await studentRepository.save(student);

    res.json({ message: 'Student unlinked successfully' });
  } catch (error: any) {
    console.error('adminUnlinkStudent error:', error);
    res.status(500).json({ message: 'Server error', error: error.message });
  }
};
