import PDFDocument from 'pdfkit';
import { Settings } from '../entities/Settings';

/**
 * Generate government-ready PDF report
 */
export async function createGovernmentReportPDF(
  reportData: any,
  reportType: 'enrollment' | 'academic' | 'attendance'
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 50, bottom: 50, left: 50, right: 50 }
      });

      const buffers: Buffer[] = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfBuffer = Buffer.concat(buffers);
        resolve(pdfBuffer);
      });
      doc.on('error', reject);

      // Header
      doc.fontSize(18)
         .fillColor('#003366')
         .text(reportData.schoolName || 'School Name', { align: 'center' });
      
      doc.moveDown(0.5);
      doc.fontSize(12)
         .fillColor('#666666')
         .text(reportData.schoolAddress || '', { align: 'center' });

      doc.moveDown(1);

      // Report Title
      let reportTitle = '';
      switch (reportType) {
        case 'enrollment':
          reportTitle = 'STUDENT ENROLLMENT REPORT';
          break;
        case 'academic':
          reportTitle = 'ACADEMIC PERFORMANCE REPORT';
          break;
        case 'attendance':
          reportTitle = 'ATTENDANCE REPORT';
          break;
      }

      doc.fontSize(16)
         .fillColor('#000000')
         .text(reportTitle, { align: 'center', underline: true });

      doc.moveDown(0.5);
      doc.fontSize(10)
         .fillColor('#666666')
         .text(`Term: ${reportData.term || 'N/A'} | Year: ${reportData.year || 'N/A'}`, { align: 'center' });
      doc.text(`Generated: ${new Date(reportData.generatedDate).toLocaleDateString()}`, { align: 'center' });

      doc.moveDown(1);

      // Report Content
      switch (reportType) {
        case 'enrollment':
          generateEnrollmentContent(doc, reportData);
          break;
        case 'academic':
          generateAcademicContent(doc, reportData);
          break;
        case 'attendance':
          generateAttendanceContent(doc, reportData);
          break;
      }

      // Footer
      const pageHeight = doc.page.height;
      const pageWidth = doc.page.width;
      doc.fontSize(8)
         .fillColor('#999999')
         .text(
           'Generated by School Management System',
           pageWidth / 2 - 100,
           pageHeight - 30,
           { width: 200, align: 'center' }
         );

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

function generateEnrollmentContent(doc: PDFKit.PDFDocument, data: any) {
  // Summary
  doc.fontSize(12)
     .fillColor('#000000')
     .text('SUMMARY', { underline: true });

  doc.moveDown(0.5);
  doc.fontSize(10)
     .fillColor('#000000')
     .text(`Total Students: ${data.totalStudents || 0}`);

  if (data.summary?.byGender) {
    doc.text(`Male: ${data.summary.byGender.male || 0}`);
    doc.text(`Female: ${data.summary.byGender.female || 0}`);
  }

  doc.moveDown(1);

  // By Class
  doc.fontSize(12)
     .fillColor('#000000')
     .text('ENROLLMENT BY CLASS', { underline: true });

  doc.moveDown(0.5);

  if (data.summary?.byClass) {
    data.summary.byClass.forEach((cls: any) => {
      doc.fontSize(10)
         .fillColor('#000000')
         .text(`${cls.className}: ${cls.count} students`);
    });
  }

  doc.moveDown(1);

  // Detailed List (if space allows)
  doc.fontSize(12)
     .fillColor('#000000')
     .text('STUDENT DETAILS', { underline: true });

  doc.moveDown(0.5);

  let yPos = doc.y;
  const startY = yPos;
  const pageHeight = doc.page.height;
  const lineHeight = 12;

  Object.keys(data.studentsByClass || {}).forEach(className => {
    // Check if we need a new page
    if (yPos > pageHeight - 100) {
      doc.addPage();
      yPos = 50;
    }

    doc.fontSize(10)
       .fillColor('#003366')
       .text(`Class: ${className}`, { continued: false });
    
    yPos += lineHeight;

    data.studentsByClass[className].forEach((student: any) => {
      if (yPos > pageHeight - 50) {
        doc.addPage();
        yPos = 50;
      }

      const studentInfo = `${student.studentNumber} - ${student.firstName} ${student.lastName} (${student.gender || 'N/A'})`;
      doc.fontSize(9)
         .fillColor('#000000')
         .text(studentInfo, { indent: 20 });
      
      yPos += lineHeight;
    });

    doc.moveDown(0.3);
    yPos += 5;
  });
}

function generateAcademicContent(doc: PDFKit.PDFDocument, data: any) {
  // Summary
  doc.fontSize(12)
     .fillColor('#000000')
     .text('SUMMARY', { underline: true });

  doc.moveDown(0.5);
  doc.fontSize(10)
     .fillColor('#000000')
     .text(`Total Students: ${data.summary?.totalStudents || 0}`);
  doc.text(`Average Performance: ${data.summary?.averagePerformance || '0.00'}%`);

  if (data.summary?.gradeDistribution) {
    doc.moveDown(0.5);
    doc.text('Grade Distribution:');
    Object.keys(data.summary.gradeDistribution).forEach(grade => {
      doc.text(`  ${grade}: ${data.summary.gradeDistribution[grade]}`, { indent: 20 });
    });
  }

  doc.moveDown(1);

  // Performance Details
  doc.fontSize(12)
     .fillColor('#000000')
     .text('STUDENT PERFORMANCE', { underline: true });

  doc.moveDown(0.5);

  // Table header
  const tableTop = doc.y;
  doc.fontSize(9)
     .fillColor('#FFFFFF')
     .rect(50, tableTop, 500, 20)
     .fill('#003366');
  
  doc.text('Student Number', 55, tableTop + 5, { width: 100 });
  doc.text('Name', 160, tableTop + 5, { width: 150 });
  doc.text('Class', 315, tableTop + 5, { width: 80 });
  doc.text('Average %', 400, tableTop + 5, { width: 80 });
  doc.text('Grade', 485, tableTop + 5, { width: 60 });

  let yPos = tableTop + 25;

  data.performanceData?.forEach((student: any) => {
    if (yPos > doc.page.height - 50) {
      doc.addPage();
      yPos = 50;
      // Redraw header
      doc.rect(50, yPos - 20, 500, 20).fill('#003366');
      doc.text('Student Number', 55, yPos - 15, { width: 100 });
      doc.text('Name', 160, yPos - 15, { width: 150 });
      doc.text('Class', 315, yPos - 15, { width: 80 });
      doc.text('Average %', 400, yPos - 15, { width: 80 });
      doc.text('Grade', 485, yPos - 15, { width: 60 });
    }

    doc.fontSize(8)
       .fillColor('#000000')
       .text(student.studentNumber || 'N/A', 55, yPos, { width: 100 });
    doc.text(`${student.firstName} ${student.lastName}`, 160, yPos, { width: 150 });
    doc.text(student.className || 'N/A', 315, yPos, { width: 80 });
    doc.text(`${student.averagePercentage}%`, 400, yPos, { width: 80 });
    doc.text(student.grade || 'N/A', 485, yPos, { width: 60 });

    yPos += 15;
  });
}

function generateAttendanceContent(doc: PDFKit.PDFDocument, data: any) {
  // Summary
  doc.fontSize(12)
     .fillColor('#000000')
     .text('SUMMARY', { underline: true });

  doc.moveDown(0.5);
  doc.fontSize(10)
     .fillColor('#000000')
     .text(`Total Students: ${data.summary?.totalStudents || 0}`);
  doc.text(`Average Attendance Rate: ${data.summary?.averageAttendanceRate || '0.00'}%`);
  doc.text(`Total Present: ${data.summary?.totalPresent || 0}`);
  doc.text(`Total Absent: ${data.summary?.totalAbsent || 0}`);

  doc.moveDown(1);

  // Attendance Details
  doc.fontSize(12)
     .fillColor('#000000')
     .text('STUDENT ATTENDANCE', { underline: true });

  doc.moveDown(0.5);

  // Table header
  const tableTop = doc.y;
  doc.fontSize(9)
     .fillColor('#FFFFFF')
     .rect(50, tableTop, 500, 20)
     .fill('#003366');
  
  doc.text('Student', 55, tableTop + 5, { width: 200 });
  doc.text('Class', 260, tableTop + 5, { width: 80 });
  doc.text('Present', 345, tableTop + 5, { width: 60 });
  doc.text('Absent', 410, tableTop + 5, { width: 60 });
  doc.text('Rate %', 475, tableTop + 5, { width: 70 });

  let yPos = tableTop + 25;

  data.attendanceData?.forEach((student: any) => {
    if (yPos > doc.page.height - 50) {
      doc.addPage();
      yPos = 50;
      // Redraw header
      doc.rect(50, yPos - 20, 500, 20).fill('#003366');
      doc.text('Student', 55, yPos - 15, { width: 200 });
      doc.text('Class', 260, yPos - 15, { width: 80 });
      doc.text('Present', 345, yPos - 15, { width: 60 });
      doc.text('Absent', 410, yPos - 15, { width: 60 });
      doc.text('Rate %', 475, yPos - 15, { width: 70 });
    }

    doc.fontSize(8)
       .fillColor('#000000')
       .text(`${student.firstName} ${student.lastName}`, 55, yPos, { width: 200 });
    doc.text(student.className || 'N/A', 260, yPos, { width: 80 });
    doc.text(student.present?.toString() || '0', 345, yPos, { width: 60 });
    doc.text(student.absent?.toString() || '0', 410, yPos, { width: 60 });
    doc.text(`${student.attendanceRate}%`, 475, yPos, { width: 70 });

    yPos += 15;
  });
}

